export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAIL = 'FETCH_HISTORY_FAIL';

export const CREATE_OR_UPDATE_HISTORY_REQUEST = 'CREATE_OR_UPDATE_HISTORY_REQUEST';
export const CREATE_OR_UPDATE_HISTORY_SUCCESS = 'CREATE_OR_UPDATE_HISTORY_SUCCESS';
export const CREATE_OR_UPDATE_HISTORY_FAIL = 'CREATE_OR_UPDATE_HISTORY_FAIL';

export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL';

export const HISTORY_ANALYTICS_REQUEST = "HISTORY_ANALYTICS_REQUEST";
export const HISTORY_ANALYTICS_SUCCESS = "HISTORY_ANALYTICS_SUCCESS";
export const HISTORY_ANALYTICS_FAIL = "HISTORY_ANALYTICS_FAIL";

export const RESET_HISTORY_SUCCESS = 'RESET_HISTORY_SUCCESS';


